// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-xiFGjR5w-cpUIcJV2x31FMishGp88YA',
    appId: '1:375833053628:web:253c27ee15e84b33fbc3b9',
    messagingSenderId: '375833053628',
    projectId: 'anonnote-47650',
    authDomain: 'anonnote-47650.firebaseapp.com',
    storageBucket: 'anonnote-47650.firebasestorage.app',
    measurementId: 'G-MQ0SCT2922',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBFF9PdFFXQnX3lz7k7htdEzt7oCqkEs',
    appId: '1:375833053628:android:31d50ef9040e8227fbc3b9',
    messagingSenderId: '375833053628',
    projectId: 'anonnote-47650',
    storageBucket: 'anonnote-47650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlSGWkvWW04soYD7vBv1-trEjGkb_8uQw',
    appId: '1:375833053628:ios:7f60a47d8110a106fbc3b9',
    messagingSenderId: '375833053628',
    projectId: 'anonnote-47650',
    storageBucket: 'anonnote-47650.firebasestorage.app',
    iosBundleId: 'com.example.anonnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlSGWkvWW04soYD7vBv1-trEjGkb_8uQw',
    appId: '1:375833053628:ios:7f60a47d8110a106fbc3b9',
    messagingSenderId: '375833053628',
    projectId: 'anonnote-47650',
    storageBucket: 'anonnote-47650.firebasestorage.app',
    iosBundleId: 'com.example.anonnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-xiFGjR5w-cpUIcJV2x31FMishGp88YA',
    appId: '1:375833053628:web:e1b0193f4ca49a4efbc3b9',
    messagingSenderId: '375833053628',
    projectId: 'anonnote-47650',
    authDomain: 'anonnote-47650.firebaseapp.com',
    storageBucket: 'anonnote-47650.firebasestorage.app',
    measurementId: 'G-32TVLE05EM',
  );
}
